M48
; DRILL file {KiCad 7.0.4} date Mon 29 May 2023 02:02:56 PM CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-29T14:02:56+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.4
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
%
G90
G05
T1
X132.334Y-58.25
X134.874Y-58.25
X137.414Y-58.25
X139.954Y-58.25
T0
M30
